name: windows

on:
  pull_request:
  push:
    branches:
      - rrrooommmaaa-7-gha
      - master
      - 'release/**'

env:
  BUILD_MODE: normal
  GPG_VERSION: stable
  CORES: 2

jobs:
  tests:
    runs-on: windows-latest
    timeout-minutes: 50
    steps:
      - name: Disable git eol translation
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v1
      - name: Determine version to build
        run: powershell.exe -ExecutionPolicy Bypass -File 'ci/version.ps1'
      - name: Check out RNP
        run: git clone --branch v${VERSION} --depth 1 https://github.com/rnpgp/rnp.git ${HOME}/rnpsrc
      - name: Add MSYS2 path
        uses: MSP-Greg/msys2-action/add_paths@master
      - name: Update MSYS2
        run: pacman-key --init
      - name: Update pacman-key
        run: pacman-key --update
      - name: Upgrade pacman
        run: pacman -Syu --noconfirm --noprogressbar --needed
      - name: Finish MSYS2 update
        run: pacman.exe -Syu --noconfirm --noprogressbar --needed
      - name: msys_install
        run: bash.exe ci/before_install.sh
      - name: build
        run: bash.exe -c ". ci/env.inc.sh && ci/main.sh"
