name: windows

on:
  pull_request:
  push:
    branches:
      - rrrooommmaaa-7-gha
      - master
      - 'release/**'

env:
  BUILD_MODE: normal
  GPG_VERSION: stable
  CORES: 2

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 50
    steps:
      - name: Disable git eol translation
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v1
      - name: Install MSYS2
        run: |
          choco.exe install MSYS2 --confirm --version 20190524.0.0.20191030
          powershell.exe -ExecutionPolicy Bypass -File ci/Get-ToolsLocation.ps1
          echo ChocolateyToolsLocation=%ChocolateyToolsLocation%
      - name: msys_install
        run: bash.exe ci/before_install.sh
      - name: Check out RNP
        run: bash.exe -c ". ci/env.inc.sh && ci/checkout.sh"
      - name: build
        run: bash.exe -c ". ci/main.sh"
